import React, { useState, useCallback } from 'react';
import { Button } from './ui/button';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Alert, AlertDescription } from './ui/alert';
import { Progress } from './ui/progress';
import { ImageUpload } from './ImageUpload';
import { AnalysisResults, AnalysisResult } from './AnalysisResults';
import { useRouter, useAuth } from '../routes/Router';
import { AuthService } from '../services/auth';
import { 
  Eye, 
  LogOut, 
  Play, 
  Brain, 
  Zap, 
  Shield,
  Clock,
  BarChart3
} from 'lucide-react';

interface UploadedImage {
  id: string;
  file: File;
  url: string;
  status: 'uploading' | 'ready' | 'processing' | 'error';
  progress: number;
}

export const DetectionPage: React.FC = () => {
  const { navigate } = useRouter();
  const { user, setUser } = useAuth();
  const [images, setImages] = useState<UploadedImage[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);
  const [analysisResults, setAnalysisResults] = useState<AnalysisResult[]>([]);
  const [processingProgress, setProcessingProgress] = useState(0);
  const [currentProcessingImage, setCurrentProcessingImage] = useState<string>('');

  // Mock TensorFlow.js model simulation
  const simulateModelInference = async (image: UploadedImage): Promise<AnalysisResult> => {
    // Simulate processing time
    await new Promise(resolve => setTimeout(resolve, 2000 + Math.random() * 1000));

    // Generate mock results
    const riskScore = Math.random();
    const riskLevel = 
      riskScore < 0.3 ? 'Benign' :
      riskScore < 0.5 ? 'Low Risk' :
      riskScore < 0.75 ? 'Medium Risk' : 'High Risk';

    // Create mock heatmap (in real app, this would be generated by Grad-CAM)
    const canvas = document.createElement('canvas');
    canvas.width = 400;
    canvas.height = 300;
    const ctx = canvas.getContext('2d')!;
    
    // Create gradient heatmap
    const gradient = ctx.createRadialGradient(200, 150, 0, 200, 150, 150);
    gradient.addColorStop(0, 'rgba(255, 0, 0, 0.8)');
    gradient.addColorStop(0.5, 'rgba(255, 255, 0, 0.6)');
    gradient.addColorStop(1, 'rgba(0, 0, 255, 0.4)');
    
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, 400, 300);
    
    const heatmapUrl = canvas.toDataURL();

    return {
      id: image.id,
      imageUrl: image.url,
      fileName: image.file.name,
      riskScore,
      riskLevel,
      confidence: 0.85 + Math.random() * 0.1,
      heatmapUrl,
      limeExplanation: {
        summary: `The model focused on ${riskLevel === 'High Risk' ? 'irregular polyp shapes and texture variations' : 'normal tissue patterns and color consistency'} contributing ${(riskScore * 100).toFixed(0)}% to the ${riskLevel.toLowerCase()} prediction.`,
        keyFeatures: [
          {
            feature: 'Tissue Texture',
            importance: 0.35 + Math.random() * 0.2,
            description: 'Surface irregularities and texture patterns in the tissue'
          },
          {
            feature: 'Color Variation',
            importance: 0.25 + Math.random() * 0.15,
            description: 'Abnormal color changes indicating potential pathology'
          },
          {
            feature: 'Morphological Features',
            importance: 0.20 + Math.random() * 0.1,
            description: 'Shape and structural characteristics of visible lesions'
          },
          {
            feature: 'Vascular Patterns',
            importance: 0.15 + Math.random() * 0.1,
            description: 'Blood vessel patterns and distribution'
          }
        ]
      },
      recommendations: 
        riskLevel === 'High Risk' ? [
          { type: 'urgent', text: 'Immediate biopsy recommended for histopathological confirmation' },
          { type: 'monitoring', text: 'Close monitoring with follow-up imaging in 3 months' }
        ] :
        riskLevel === 'Medium Risk' ? [
          { type: 'monitoring', text: 'Consider biopsy and schedule follow-up in 6 months' },
          { type: 'routine', text: 'Continue regular screening protocol' }
        ] :
        riskLevel === 'Low Risk' ? [
          { type: 'monitoring', text: 'Monitor during next routine screening' },
          { type: 'routine', text: 'Continue standard screening interval' }
        ] : [
          { type: 'routine', text: 'Normal findings - continue routine screening schedule' }
        ],
      processingTime: 1500 + Math.random() * 1000
    };
  };

  const processImages = useCallback(async () => {
    const readyImages = images.filter(img => img.status === 'ready');
    
    if (readyImages.length === 0) {
      alert('No images ready for processing');
      return;
    }

    setIsProcessing(true);
    setProcessingProgress(0);
    setAnalysisResults([]);

    const results: AnalysisResult[] = [];

    for (let i = 0; i < readyImages.length; i++) {
      const image = readyImages[i];
      setCurrentProcessingImage(image.file.name);
      
      // Update image status
      setImages(prev => prev.map(img => 
        img.id === image.id ? { ...img, status: 'processing' } : img
      ));

      try {
        const result = await simulateModelInference(image);
        results.push(result);
        
        // Update progress
        setProcessingProgress((i + 1) / readyImages.length * 100);
      } catch (error) {
        console.error('Processing failed for', image.file.name, error);
        
        // Update image status to error
        setImages(prev => prev.map(img => 
          img.id === image.id ? { ...img, status: 'error' } : img
        ));
      }
    }

    setAnalysisResults(results);
    setIsProcessing(false);
    setCurrentProcessingImage('');
  }, [images]);

  const handleImagesChange = useCallback((newImages: UploadedImage[]) => {
    setImages(newImages);
    // Clear previous results when images change
    if (analysisResults.length > 0 && newImages.length === 0) {
      setAnalysisResults([]);
    }
  }, [analysisResults.length]);

  const handleLogout = () => {
    AuthService.logout();
    setUser(null);
    navigate('/');
  };

  const readyImagesCount = images.filter(img => img.status === 'ready').length;
  const hasResults = analysisResults.length > 0;

  // Redirect if not authenticated
  if (!user?.isAuthenticated) {
    navigate('/login');
    return null;
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-white">
      {/* Header */}
      <div className="bg-white/80 backdrop-blur-sm border-b border-blue-100 sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2">
                <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
                  <Eye className="w-5 h-5 text-white" />
                </div>
                <span className="text-xl font-bold text-blue-900">ColoVision</span>
              </div>
              <Badge variant="outline" className="border-green-200 text-green-700">
                <Shield className="w-3 h-3 mr-1" />
                Secure Session
              </Badge>
            </div>
            
            <div className="flex items-center space-x-4">
              <div className="text-sm text-gray-600">
                Welcome, <span className="font-medium">{user.email}</span>
              </div>
              <Button 
                variant="outline" 
                onClick={handleLogout}
                className="border-blue-200 text-blue-700 hover:bg-blue-50"
              >
                <LogOut className="w-4 h-4 mr-2" />
                Logout
              </Button>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="space-y-8">
          {/* Page Header */}
          <div className="text-center space-y-4">
            <h1 className="text-3xl font-bold text-gray-900">
              AI-Powered Colorectal Cancer Detection
            </h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Upload colonoscopy images for real-time analysis using advanced deep learning models 
              with explainable AI insights
            </p>
            
            <div className="flex flex-wrap justify-center gap-4 mt-6">
              <div className="flex items-center space-x-2 text-sm text-gray-600">
                <Brain className="w-4 h-4 text-blue-600" />
                <span>EfficientNet-B0 Model</span>
              </div>
              <div className="flex items-center space-x-2 text-sm text-gray-600">
                <Zap className="w-4 h-4 text-yellow-600" />
                <span>Real-time Processing</span>
              </div>
              <div className="flex items-center space-x-2 text-sm text-gray-600">
                <Shield className="w-4 h-4 text-green-600" />
                <span>Local Processing</span>
              </div>
              <div className="flex items-center space-x-2 text-sm text-gray-600">
                <Eye className="w-4 h-4 text-purple-600" />
                <span>Explainable AI</span>
              </div>
            </div>
          </div>

          {/* Processing Status */}
          {isProcessing && (
            <Card className="border-blue-200 bg-blue-50">
              <CardContent className="p-6">
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <Brain className="w-5 h-5 text-blue-600 animate-pulse" />
                      <span className="font-semibold text-blue-900">Processing Images...</span>
                    </div>
                    <Badge variant="outline" className="border-blue-300 text-blue-700">
                      <Clock className="w-3 h-3 mr-1" />
                      {Math.round((100 - processingProgress) / 20)} min remaining
                    </Badge>
                  </div>
                  
                  <Progress value={processingProgress} className="h-3" />
                  
                  <div className="text-sm text-blue-700">
                    Currently analyzing: <span className="font-medium">{currentProcessingImage}</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Image Upload Section */}
          <Card className="border-blue-100">
            <CardHeader>
              <CardTitle className="flex items-center space-x-2">
                <BarChart3 className="w-5 h-5 text-blue-600" />
                <span>Image Analysis</span>
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <ImageUpload onImagesChange={handleImagesChange} />
              
              {images.length > 0 && (
                <div className="flex items-center justify-between p-4 bg-blue-50 rounded-lg">
                  <div className="flex items-center space-x-4">
                    <div className="text-sm text-blue-700">
                      <span className="font-medium">{readyImagesCount}</span> images ready for analysis
                    </div>
                    {hasResults && (
                      <Badge className="bg-green-100 text-green-700 border-green-200">
                        {analysisResults.length} results available
                      </Badge>
                    )}
                  </div>
                  
                  <Button
                    onClick={processImages}
                    disabled={readyImagesCount === 0 || isProcessing}
                    className="bg-blue-600 hover:bg-blue-700"
                  >
                    <Play className="w-4 h-4 mr-2" />
                    {isProcessing ? 'Processing...' : 'Analyze All Images'}
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Analysis Results */}
          {hasResults && (
            <AnalysisResults 
              results={analysisResults}
              onClose={() => setAnalysisResults([])}
            />
          )}

          {/* Help Information */}
          <Alert>
            <Shield className="w-4 h-4" />
            <AlertDescription>
              <strong>Privacy Notice:</strong> All image processing happens locally on your device using TensorFlow.js. 
              No images are uploaded to servers or stored remotely. Results are generated in real-time without 
              compromising patient privacy or data security.
            </AlertDescription>
          </Alert>
        </div>
      </div>
    </div>
  );
};